version: "3.9"
services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - dev.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-db-data:/var/lib/postgresql/data/pgdata
